<?php
/**
 * Plugin Name: Caspian — Service×City Matrix
 * Description: Template-driven virtual cross-pages at /{city}-{appliance}-repair/. ACF/data-driven. 36 cities × 8 services = 288 pages generated by single template. No CPT entries created. Reuses caspian_brand_logos() for brand grid.
 * Version: 1.3
 *
 * v1.3 fixes (critical layout):
 *   - v1.2 shared full-bleed selector (applied to 8 sections individually) caused
 *     the entire page to collapse into the left half of the viewport — Astra was
 *     defaulting virtual-render pages to a sidebar layout, and per-section -50vw
 *     margins clipped against the narrow content container.
 *   - Refactored: full-bleed is now applied to ONLY the outer .caspian-matrix-page
 *     wrapper (single anchor point). Inner sections flow naturally at 100% width.
 *   - Added Astra layout filters to force no-sidebar + page-builder layout for
 *     matrix renders. Also belts-and-suspenders body classes.
 *
 * v1.2 fixes:
 *   - Call buttons now display "Call Now" (phone number hidden, but stays in tel: href).
 *     Matches header CTA pattern site-wide.
 *   - All sections (hero, symptoms, local, why, brands, faq, links, cta-final) now
 *     full-bleed via shared selector — was previously hero-only. Preserves site
 *     design harmony: dark sections (cta-final, why) now span full viewport.
 *
 * v1.1 fix:
 *   - Removed virtual-post hack (setup_postdata + $wp_query fake post) — was triggering fatal
 *     incompat with Yoast/Astra causing HTTP 500 on render.
 *   - Switched to direct render at template_redirect: get_header + echo render + get_footer + exit.
 *     Same pattern as standalone brand pages.
 *   - Added try/catch around render with error_log + graceful fallback message.
 *   - Document title now set via pre_get_document_title + document_title_parts filters.
 *
 * Architecture:
 *   - Single rewrite rule with explicit service alternation -> captures (city, service) tuple
 *   - Virtual post fabricated at template_redirect (no DB entries)
 *   - Astra header/footer + the_content filter pipeline -> consistent layout with rest of site
 *   - Yoast wpseo_title + wpseo_metadesc filters per cross-page
 *   - FAQ schema injected at wp_head
 *   - Locked design system (Royal Sapphire palette)
 *
 * URL examples (all 288 work):
 *   /hamilton-refrigerator-repair/
 *   /burlington-washing-machine-repair/
 *   /toronto-dishwasher-repair/
 *   /oakville-gas-appliance-repair/
 *   /stoney-creek-dryer-repair/
 *   /richmond-hill-oven-repair/
 */

if ( ! defined( 'ABSPATH' ) ) exit;

/* ============================================================
   SERVICE DEFINITIONS — 8 services × 6 symptoms each
   ============================================================ */
function caspian_matrix_services() {
    return array(
        'refrigerator' => array(
            'label'       => 'Refrigerator',
            'label_short' => 'fridge',
            'parent_url'  => '/refrigerator-repair/',
            'tssa'        => false,
            'symptoms'    => array(
                array( 'title' => 'Not Cooling',           'desc' => 'Warm fridge or freezer, compressor or sealed-system failure.' ),
                array( 'title' => 'Ice Maker Not Working', 'desc' => 'No ice production, slow output, or leaking water lines.' ),
                array( 'title' => 'Water Dispenser Issues','desc' => 'No water, slow flow, or leaks at the dispenser door.' ),
                array( 'title' => 'Strange Noises',        'desc' => 'Loud humming, clicking, or buzzing from the compressor or fans.' ),
                array( 'title' => 'Frost Build-Up',        'desc' => 'Defrost system failure — ice buildup in freezer or fresh-food section.' ),
                array( 'title' => 'Leaks on the Floor',    'desc' => 'Blocked drain line, faulty water inlet valve, or worn door seals.' ),
            ),
        ),
        'washing-machine' => array(
            'label'       => 'Washing Machine',
            'label_short' => 'washer',
            'parent_url'  => '/washing-machine-repair/',
            'tssa'        => false,
            'symptoms'    => array(
                array( 'title' => 'Won\'t Drain',          'desc' => 'Standing water in drum, clogged drain pump or hose.' ),
                array( 'title' => 'Won\'t Spin',           'desc' => 'Drum won\'t agitate or spin out water — motor or coupler failure.' ),
                array( 'title' => 'Leaking Water',         'desc' => 'Water on floor during cycle, worn seals, hoses, or pump.' ),
                array( 'title' => 'Error Codes',           'desc' => 'Display showing fault codes — control-board or sensor diagnosis.' ),
                array( 'title' => 'Drum & Bearing Issues', 'desc' => 'Banging, off-balance loads, worn bearings or suspension rods.' ),
                array( 'title' => 'Won\'t Start',          'desc' => 'No power, door latch failure, or control panel unresponsive.' ),
            ),
        ),
        'dishwasher' => array(
            'label'       => 'Dishwasher',
            'label_short' => 'dishwasher',
            'parent_url'  => '/dishwasher-repair/',
            'tssa'        => false,
            'symptoms'    => array(
                array( 'title' => 'Not Cleaning Dishes',   'desc' => 'Spray arms blocked, wash motor weak, dirty filter or pump.' ),
                array( 'title' => 'Not Draining',          'desc' => 'Standing water at bottom — clogged drain pump or hose.' ),
                array( 'title' => 'Leaking Water',         'desc' => 'Water under unit — worn door seals or faulty inlet valve.' ),
                array( 'title' => 'Error Codes',           'desc' => 'Display fault codes pointing to control board or sensors.' ),
                array( 'title' => 'Control Board Failure', 'desc' => 'Buttons unresponsive, cycles won\'t start or complete.' ),
                array( 'title' => 'Door & Latch Issues',   'desc' => 'Latch broken, door springs worn, door won\'t close securely.' ),
            ),
        ),
        'dryer' => array(
            'label'       => 'Dryer',
            'label_short' => 'dryer',
            'parent_url'  => '/dryer-repair/',
            'tssa'        => true,  // gas dryers need TSSA disclaimer
            'symptoms'    => array(
                array( 'title' => 'No Heat',               'desc' => 'Drum spins but clothes stay wet — heating element or thermal fuse.' ),
                array( 'title' => 'Takes Too Long to Dry', 'desc' => 'Clogged vent, weak airflow, or partial element failure.' ),
                array( 'title' => 'Drum Not Turning',      'desc' => 'Motor runs but drum stays still — broken belt or idler pulley.' ),
                array( 'title' => 'Loud Noises',           'desc' => 'Squealing, thumping, or grinding from worn rollers or bearings.' ),
                array( 'title' => 'Vent & Airflow Issues', 'desc' => 'Lint buildup, blocked exhaust — a real fire hazard if ignored.' ),
                array( 'title' => 'Won\'t Start',          'desc' => 'No response — door switch, thermal fuse, or start-circuit failure.' ),
            ),
        ),
        'oven' => array(
            'label'       => 'Oven',
            'label_short' => 'oven',
            'parent_url'  => '/oven-repair/',
            'tssa'        => true,
            'symptoms'    => array(
                array( 'title' => 'Not Heating',           'desc' => 'Bake or broil element failure, thermostat or igniter issues.' ),
                array( 'title' => 'Uneven Baking',         'desc' => 'Hot spots, fan motor failure, or temperature sensor drift.' ),
                array( 'title' => 'Door Won\'t Close',     'desc' => 'Worn hinges, broken springs, or degraded door seal.' ),
                array( 'title' => 'Display & Controls',    'desc' => 'Touchpad unresponsive, error codes, control-board failure.' ),
                array( 'title' => 'Element Burned Out',    'desc' => 'Visible damage to bake or broil element — replacement needed.' ),
                array( 'title' => 'Self-Clean Cycle Faults','desc' => 'Door lock stuck or control-board fault after cleaning cycle.' ),
            ),
        ),
        'stove' => array(
            'label'       => 'Stove',
            'label_short' => 'stove',
            'parent_url'  => '/stove-repair/',
            'tssa'        => true,
            'symptoms'    => array(
                array( 'title' => 'Burner Won\'t Heat',    'desc' => 'Electric coil or surface element failure, switch issues.' ),
                array( 'title' => 'Continuous Sparking',   'desc' => 'Gas igniter clicking nonstop — ignition switch or moisture.' ),
                array( 'title' => 'Igniter Won\'t Light',  'desc' => 'Gas burner won\'t ignite — weak spark or blocked port.' ),
                array( 'title' => 'Knob & Switch Issues',  'desc' => 'Broken knobs, faulty surface switches, control wiring.' ),
                array( 'title' => 'Control Board Failure', 'desc' => 'Touch controls unresponsive, electronic burner-control fault.' ),
                array( 'title' => 'Glass Cooktop Damage',  'desc' => 'Cracked surface, burner element issues, regulator failure.' ),
            ),
        ),
        'freezer' => array(
            'label'       => 'Freezer',
            'label_short' => 'freezer',
            'parent_url'  => '/freezer-repair/',
            'tssa'        => false,
            'symptoms'    => array(
                array( 'title' => 'Not Freezing',          'desc' => 'Compressor or sealed-system failure, sensor drift.' ),
                array( 'title' => 'Frost Build-Up',        'desc' => 'Defrost heater or thermostat failure — ice accumulation.' ),
                array( 'title' => 'Door Won\'t Seal',      'desc' => 'Worn gasket or hinge issues — condensation forming inside.' ),
                array( 'title' => 'Compressor Noises',     'desc' => 'Loud humming, clicking, or buzzing — compressor or relay.' ),
                array( 'title' => 'Water Leaks',           'desc' => 'Clogged defrost drain — water on floor inside or below unit.' ),
                array( 'title' => 'Defrost Cycle Failure', 'desc' => 'Manual defrost needed often, automatic cycle not running.' ),
            ),
        ),
        'gas-appliance' => array(
            'label'       => 'Gas Appliance',
            'label_short' => 'gas appliance',
            'parent_url'  => '/gas-appliance-repair/',
            'tssa'        => true,
            'symptoms'    => array(
                array( 'title' => 'Pilot Light Won\'t Stay Lit', 'desc' => 'Thermocouple failure, gas valve, or air supply issue.' ),
                array( 'title' => 'Igniter Not Sparking',        'desc' => 'Electronic igniter failure or faulty control module.' ),
                array( 'title' => 'Gas Valve Problems',          'desc' => 'Valve not opening, low gas pressure, safety shutoff trip.' ),
                array( 'title' => 'Weak or Yellow Flame',        'desc' => 'Air-mix problem, blocked burner ports, regulator failure.' ),
                array( 'title' => 'Safety Shut-Off',             'desc' => 'Appliance shuts off mid-cycle — safety sensor diagnosis.' ),
                array( 'title' => 'Gas Smell or Leak',           'desc' => 'Call your gas utility first, then a TSSA-licensed technician.' ),
            ),
        ),
    );
}

/* ============================================================
   BRANDS — same 16 used in city picker (locked)
   ============================================================ */
function caspian_matrix_brands() {
    return array(
        array( 'slug' => 'samsung-appliance-repair',       'label' => 'Samsung' ),
        array( 'slug' => 'lg-appliance-repair',            'label' => 'LG' ),
        array( 'slug' => 'whirlpool-appliance-repair',     'label' => 'Whirlpool' ),
        array( 'slug' => 'kitchenaid-appliance-repair',    'label' => 'KitchenAid' ),
        array( 'slug' => 'bosch-appliance-repair',         'label' => 'Bosch' ),
        array( 'slug' => 'maytag-appliance-repair',        'label' => 'Maytag' ),
        array( 'slug' => 'frigidaire-appliance-repair',    'label' => 'Frigidaire' ),
        array( 'slug' => 'ge-appliance-repair',            'label' => 'GE' ),
        array( 'slug' => 'kenmore-appliance-repair',       'label' => 'Kenmore' ),
        array( 'slug' => 'electrolux-appliance-repair',    'label' => 'Electrolux' ),
        array( 'slug' => 'amana-appliance-repair',         'label' => 'Amana' ),
        array( 'slug' => 'jennair-appliance-repair',       'label' => 'Jenn-Air' ),
        array( 'slug' => 'thermador-appliance-repair',     'label' => 'Thermador' ),
        array( 'slug' => 'viking-appliance-repair',        'label' => 'Viking' ),
        array( 'slug' => 'wolf-appliance-repair',          'label' => 'Wolf' ),
        array( 'slug' => 'fisher-paykel-appliance-repair', 'label' => 'Fisher & Paykel' ),
    );
}

/* ============================================================
   REWRITE RULES + QUERY VARS
   ============================================================ */
add_action( 'init', function() {
    // Matrix rule (explicit service alternation, 'top' priority to beat city CPT regex)
    add_rewrite_rule(
        '^([a-z][a-z0-9-]*)-(refrigerator|washing-machine|dishwasher|dryer|oven|stove|freezer|gas-appliance)-repair/?$',
        'index.php?caspian_svc=$matches[2]&caspian_city=$matches[1]',
        'top'
    );
}, 11 );

add_filter( 'query_vars', function( $vars ) {
    $vars[] = 'caspian_svc';
    $vars[] = 'caspian_city';
    return $vars;
});

/* ============================================================
   CITY LOOKUP — try multiple CPT names + fallback
   ============================================================ */
function caspian_matrix_get_city( $city_slug ) {
    $candidates = array( 'city', 'caspian_city', 'cities' );
    foreach ( $candidates as $cpt ) {
        if ( ! post_type_exists( $cpt ) ) continue;
        // City CPT post name is typically "<slug>-appliance-repair"
        $p = get_page_by_path( $city_slug . '-appliance-repair', OBJECT, $cpt );
        if ( $p && $p->post_status === 'publish' ) return $p;
        // Fallback: just the slug
        $p = get_page_by_path( $city_slug, OBJECT, $cpt );
        if ( $p && $p->post_status === 'publish' ) return $p;
    }
    // Last-resort generic lookup
    $posts = get_posts( array(
        'post_type'      => 'any',
        'name'           => $city_slug . '-appliance-repair',
        'numberposts'    => 1,
        'post_status'    => 'publish',
        'suppress_filters' => false,
    ));
    return $posts ? $posts[0] : null;
}

/* Pull a clean city name out of the post title (strip trailing "appliance repair") */
function caspian_matrix_city_name( $city_post ) {
    $name = $city_post->post_title;
    $name = preg_replace( '/\s*appliance\s*repair\s*$/i', '', $name );
    $name = trim( $name );
    return $name ?: $city_post->post_title;
}

/* City slug -> city URL (e.g. "hamilton" -> "/hamilton-appliance-repair/") */
function caspian_matrix_city_url( $city_slug ) {
    return '/' . sanitize_title( $city_slug ) . '-appliance-repair/';
}

/* ============================================================
   GLOBAL CONTEXT (set by intercept; used by filters/schema)
   ============================================================ */
global $caspian_matrix_ctx;
$caspian_matrix_ctx = null;

/* ============================================================
   TEMPLATE REDIRECT — DIRECT RENDER
   Bypasses WP template hierarchy. get_header + echo + get_footer + exit.
   Same pattern as brand pages. No virtual post (fatal incompat with Yoast/Astra).
   ============================================================ */
add_action( 'template_redirect', 'caspian_matrix_intercept', 5 );

function caspian_matrix_intercept() {
    $svc_key   = get_query_var( 'caspian_svc' );
    $city_slug = get_query_var( 'caspian_city' );

    if ( empty( $svc_key ) || empty( $city_slug ) ) return;

    $services = caspian_matrix_services();
    if ( ! isset( $services[ $svc_key ] ) ) return;

    $city = caspian_matrix_get_city( $city_slug );
    if ( ! $city ) {
        // City not found -> 404
        global $wp_query;
        $wp_query->set_404();
        status_header( 404 );
        nocache_headers();
        return;
    }

    $svc        = $services[ $svc_key ];
    $city_name  = caspian_matrix_city_name( $city );
    $appliance  = $svc['label'];
    $page_title = $appliance . ' Repair in ' . $city_name;

    // Set global context for Yoast filters + FAQ schema
    global $caspian_matrix_ctx, $wp_query;
    $caspian_matrix_ctx = array(
        'city'      => $city,
        'city_name' => $city_name,
        'city_slug' => $city_slug,
        'svc_key'   => $svc_key,
        'svc'       => $svc,
        'appliance' => $appliance,
        'title'     => $page_title,
    );

    // Tell WP this is NOT a 404
    $wp_query->is_404 = false;
    status_header( 200 );
    nocache_headers();

    // FAQ schema in head
    add_action( 'wp_head', 'caspian_matrix_faq_schema', 50 );

    // Document title override (Astra/WP core)
    add_filter( 'document_title_parts', function( $parts ) use ( $page_title ) {
        $parts['title'] = $page_title;
        unset( $parts['tagline'] );
        return $parts;
    }, 99 );
    add_filter( 'pre_get_document_title', function( $title ) use ( $page_title ) {
        return $page_title . ' | Caspian Appliance Repair';
    }, 99 );

    // Suppress Astra page title bar (we render own hero)
    add_filter( 'astra_the_title_enabled', '__return_false', 999 );

    // Force Astra to render no-sidebar + page-builder (full-width) layout for matrix pages.
    // Without this, virtual-page rendering can fall into a default sidebar layout,
    // leaving the right half of the viewport empty.
    add_filter( 'astra_page_layout',                                  function() { return 'no-sidebar'; },   9999 );
    add_filter( 'astra_sidebar_layout',                               function() { return 'no-sidebar'; },   9999 );
    add_filter( 'astra_get_option_site-sidebar-layout',               function() { return 'no-sidebar'; },   9999 );
    add_filter( 'astra_get_option_single-page-sidebar-layout',        function() { return 'no-sidebar'; },   9999 );
    add_filter( 'astra_get_option_single-post-sidebar-layout',        function() { return 'no-sidebar'; },   9999 );
    add_filter( 'astra_get_content_layout',                           function() { return 'page-builder'; }, 9999 );
    add_filter( 'astra_get_option_site-content-layout',               function() { return 'page-builder'; }, 9999 );
    add_filter( 'astra_get_option_single-page-content-layout',        function() { return 'page-builder'; }, 9999 );
    add_filter( 'astra_get_option_single-post-content-layout',        function() { return 'page-builder'; }, 9999 );
    // Belt-and-suspenders body classes
    add_filter( 'body_class', function( $classes ) {
        $classes[] = 'ast-no-sidebar';
        $classes[] = 'ast-page-builder-template';
        $classes[] = 'ast-single-post';
        $classes[] = 'caspian-matrix-body';
        return $classes;
    }, 9999 );

    // Direct render — no virtual post, no the_content filter
    try {
        get_header();
        echo caspian_matrix_render( $caspian_matrix_ctx );
        get_footer();
    } catch ( Throwable $e ) {
        error_log( 'CASPIAN-MATRIX render error on /' . $city_slug . '-' . $svc_key . '-repair/: ' . $e->getMessage() . ' @ ' . $e->getFile() . ':' . $e->getLine() );
        echo '<div style="max-width:800px;margin:60px auto;padding:30px;background:#f9f9f9;border:1px solid #ddd;border-radius:6px;text-align:center;">';
        echo '<h2 style="color:#062963;">' . esc_html( $page_title ) . '</h2>';
        echo '<p>For service, please call <a href="tel:+14167325905" style="color:#0B3D91;font-weight:600;">(416) 732-5905</a>.</p>';
        echo '</div>';
    }
    exit;
}

/* ============================================================
   YOAST META TITLE / DESCRIPTION
   ============================================================ */
add_filter( 'wpseo_title', function( $title ) {
    global $caspian_matrix_ctx;
    if ( ! $caspian_matrix_ctx ) return $title;
    return sprintf( '%s %s Repair | Same-Day Service | Caspian',
        $caspian_matrix_ctx['city_name'],
        $caspian_matrix_ctx['appliance']
    );
}, 99 );

add_filter( 'wpseo_metadesc', function( $desc ) {
    global $caspian_matrix_ctx;
    if ( ! $caspian_matrix_ctx ) return $desc;
    return sprintf(
        'Same-day %s repair in %s by local technicians. All major brands. BBB A Accredited, ★4.8/220+ Google Reviews. 90-day warranty. Call (416) 732-5905.',
        strtolower( $caspian_matrix_ctx['svc']['label'] ),
        $caspian_matrix_ctx['city_name']
    );
}, 99 );

add_filter( 'wpseo_canonical', function( $canon ) {
    global $caspian_matrix_ctx;
    if ( ! $caspian_matrix_ctx ) return $canon;
    return home_url( '/' . $caspian_matrix_ctx['city_slug'] . '-' . $caspian_matrix_ctx['svc_key'] . '-repair/' );
}, 99 );

add_filter( 'wpseo_opengraph_url', function( $url ) {
    global $caspian_matrix_ctx;
    if ( ! $caspian_matrix_ctx ) return $url;
    return home_url( '/' . $caspian_matrix_ctx['city_slug'] . '-' . $caspian_matrix_ctx['svc_key'] . '-repair/' );
}, 99 );

/* ============================================================
   FAQ SCHEMA (JSON-LD in head)
   ============================================================ */
function caspian_matrix_faq_schema() {
    global $caspian_matrix_ctx;
    if ( ! $caspian_matrix_ctx ) return;

    $faqs = caspian_matrix_faqs( $caspian_matrix_ctx );
    if ( empty( $faqs ) ) return;

    $items = array();
    foreach ( $faqs as $f ) {
        $items[] = array(
            '@type'          => 'Question',
            'name'           => $f['q'],
            'acceptedAnswer' => array(
                '@type' => 'Answer',
                'text'  => wp_strip_all_tags( $f['a'] ),
            ),
        );
    }
    $schema = array(
        '@context'   => 'https://schema.org',
        '@type'      => 'FAQPage',
        'mainEntity' => $items,
    );
    echo "\n<script type=\"application/ld+json\">" . wp_json_encode( $schema, JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE ) . "</script>\n";
}

/* Generate 6 FAQs unique to this city+service combo */
function caspian_matrix_faqs( $ctx ) {
    $city      = $ctx['city_name'];
    $appliance = $ctx['appliance'];
    $applow    = strtolower( $appliance );
    $is_gas    = ! empty( $ctx['svc']['tssa'] );

    $faqs = array(
        array(
            'q' => sprintf( 'Do you repair %s in %s?', $applow, $city ),
            'a' => sprintf( 'Yes — Caspian technicians serve %s every day, with same-day appointments often available. We work on all major %s brands including Samsung, LG, Whirlpool, KitchenAid, Bosch, Maytag, Frigidaire, GE, and more.', $city, $applow ),
        ),
        array(
            'q' => sprintf( 'How much does %s repair cost in %s?', $applow, $city ),
            'a' => sprintf( 'Pricing is quoted in writing after on-site diagnosis. Each %s repair is different — element replacement on an oven, for example, is very different from a sealed-system fridge repair. Our technician will diagnose the issue and give you a firm price before any work begins.', $applow ),
        ),
        array(
            'q' => sprintf( 'What %s brands do you service in %s?', $applow, $city ),
            'a' => sprintf( 'We service all major %s brands in %s: Samsung, LG, Whirlpool, KitchenAid, Bosch, Maytag, Frigidaire, GE, Kenmore, Electrolux, Amana, Jenn-Air, Thermador, Viking, Wolf, and Fisher & Paykel. We are independent and not factory-authorized for warranty work — we provide quality out-of-warranty repairs.', $applow, $city ),
        ),
        array(
            'q' => sprintf( 'Do you offer same-day %s repair in %s?', $applow, $city ),
            'a' => sprintf( 'Yes — same-day %s service in %s is available most days, subject to technician availability and parts on hand. Call (416) 732-5905 or book online and our dispatch will confirm the soonest slot.', $applow, $city ),
        ),
        array(
            'q' => 'Are you BBB Accredited?',
            'a' => 'Yes, Caspian Appliance Repair is BBB A Accredited (Hamilton, ON). You can view our profile and complaint history on the Better Business Bureau website.',
        ),
        array(
            'q' => sprintf( 'Do you offer a warranty on %s repairs?', $applow ),
            'a' => 'Yes — every repair is backed by a 90-day parts and labour warranty. If the same issue returns within 90 days, we return at no charge.',
        ),
    );

    if ( $is_gas ) {
        $faqs[] = array(
            'q' => sprintf( 'Are your technicians TSSA-licensed for gas %s repair?', $applow ),
            'a' => sprintf( 'Yes — all gas-line work on %s in %s is performed by TSSA-licensed partner technicians, in compliance with Ontario regulations.', $applow, $city ),
        );
    }

    return $faqs;
}

/* ============================================================
   RENDER — main template
   ============================================================ */
function caspian_matrix_render( $ctx ) {
    $city       = $ctx['city'];
    $city_name  = $ctx['city_name'];
    $city_slug  = $ctx['city_slug'];
    $svc        = $ctx['svc'];
    $svc_key    = $ctx['svc_key'];
    $appliance  = $ctx['appliance'];
    $applow     = strtolower( $appliance );
    $applow_one = $svc['label_short'];
    $is_gas     = ! empty( $svc['tssa'] );

    $city_intro = function_exists( 'get_field' ) ? get_field( 'city_intro', $city->ID ) : '';
    $city_intro = is_string( $city_intro ) ? trim( $city_intro ) : '';

    $brand_logos = function_exists( 'caspian_brand_logos' ) ? caspian_brand_logos() : array();
    $brands      = caspian_matrix_brands();
    $faqs        = caspian_matrix_faqs( $ctx );

    /* Internal-link matrix data */
    $other_services = array();
    foreach ( caspian_matrix_services() as $k => $s ) {
        if ( $k === $svc_key ) continue;
        $other_services[] = array(
            'url'   => '/' . $city_slug . '-' . $k . '-repair/',
            'label' => $s['label'] . ' Repair',
        );
    }

    /* Nearby cities for SAME service */
    $nearby_cities = array();
    if ( function_exists( 'get_field' ) ) {
        $nearby = get_field( 'nearby_cities', $city->ID );
        if ( is_array( $nearby ) ) {
            foreach ( $nearby as $nb ) {
                $nb_post = is_object( $nb ) ? $nb : get_post( $nb );
                if ( ! $nb_post ) continue;
                $nb_name = caspian_matrix_city_name( $nb_post );
                $nb_slug = preg_replace( '/-appliance-repair$/', '', $nb_post->post_name );
                $nearby_cities[] = array(
                    'url'   => '/' . $nb_slug . '-' . $svc_key . '-repair/',
                    'label' => $appliance . ' Repair in ' . $nb_name,
                );
            }
        }
    }
    /* Fallback: use caspian_city_nearby_fallback() if available and ACF empty */
    if ( empty( $nearby_cities ) && function_exists( 'caspian_city_nearby_fallback' ) ) {
        $fb = caspian_city_nearby_fallback( $city_slug );
        if ( is_array( $fb ) ) {
            foreach ( array_slice( $fb, 0, 8 ) as $row ) {
                if ( empty( $row['slug'] ) ) continue;
                $nearby_cities[] = array(
                    'url'   => '/' . $row['slug'] . '-' . $svc_key . '-repair/',
                    'label' => $appliance . ' Repair in ' . ( $row['name'] ?? $row['slug'] ),
                );
            }
        }
    }

    ob_start();
    ?>
<style>
/* ============================================================
   CASPIAN — SERVICE×CITY MATRIX PAGE
   Royal Sapphire palette (locked)
   ============================================================ */
.caspian-matrix-page * { box-sizing: border-box; }
.caspian-matrix-page {
    font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
    color: #1a1a1a;
    line-height: 1.6;
    /* Single full-bleed point: outer wrapper breaks out of Astra's content
       constraint. All inner sections flow naturally at 100% width. */
    position: relative;
    left: 50%;
    right: 50%;
    margin-left: -50vw;
    margin-right: -50vw;
    width: 100vw;
    max-width: 100vw;
    overflow-x: hidden;
}
.caspian-matrix-page a { color: #0B3D91; text-decoration: none; }
.caspian-matrix-page a:hover { text-decoration: underline; }

/* Each section is a normal block inside the full-bleed wrapper — spans 100% of wrapper = 100% of viewport. */

/* ============================================================
   BLOCK 1: HERO (full-bleed sapphire)
   ============================================================ */
.cmx-hero {
    background: linear-gradient(135deg, #0B3D91 0%, #062963 100%);
    color: #fff !important;
    padding: 70px 20px 60px;
}
.cmx-hero-inner { max-width: 1100px; margin: 0 auto; }
.cmx-kicker {
    color: #7BC4F0 !important;
    font-size: 14px;
    font-weight: 600;
    text-transform: uppercase;
    letter-spacing: 1.5px;
    margin: 0 0 12px;
}
.cmx-hero h1 {
    color: #fff !important;
    font-size: 42px;
    font-weight: 700;
    line-height: 1.15;
    margin: 0 0 18px;
}
.cmx-subtitle {
    color: #b8d0eb !important;
    font-size: 18px;
    margin: 0 0 28px;
    max-width: 720px;
}
.cmx-trust-pills {
    display: flex;
    flex-wrap: wrap;
    gap: 10px 14px;
    list-style: none;
    padding: 0;
    margin: 0 0 30px;
}
.cmx-trust-pills li {
    color: #fff !important;
    font-size: 13px;
    font-weight: 600;
    background: rgba(255,255,255,0.10);
    border: 1px solid rgba(255,255,255,0.25);
    border-radius: 999px;
    padding: 8px 16px;
}
.cmx-cta { display: flex; flex-wrap: wrap; gap: 12px; }
.cmx-btn-call, .cmx-btn-book {
    display: inline-block;
    padding: 14px 24px;
    border-radius: 6px;
    font-weight: 700;
    font-size: 15px;
    text-decoration: none !important;
    transition: transform .15s, box-shadow .15s;
}
.cmx-btn-call { background: #1ca64c; color: #fff !important; }
.cmx-btn-book { background: #e0382a; color: #fff !important; }
.cmx-btn-call:hover, .cmx-btn-book:hover { transform: translateY(-1px); box-shadow: 0 6px 16px rgba(0,0,0,0.25); }

/* ============================================================
   BLOCK 2: SYMPTOMS
   ============================================================ */
.cmx-symptoms { padding: 60px 20px; background: #fff; }
.cmx-inner { max-width: 1100px; margin: 0 auto; }
.cmx-symptoms h2,
.cmx-brands h2,
.cmx-faq h2,
.cmx-links h2 {
    font-size: 28px;
    color: #062963;
    margin: 0 0 8px;
    font-weight: 700;
}
.cmx-section-lead { color: #555; font-size: 16px; margin: 0 0 32px; max-width: 760px; }
.cmx-symptom-grid {
    display: grid;
    grid-template-columns: repeat(3, 1fr);
    gap: 18px;
}
.cmx-symptom-card {
    background: #EBF1FA;
    border-left: 4px solid #2E80D1;
    padding: 22px 22px 20px;
    border-radius: 6px;
}
.cmx-symptom-card h3 {
    margin: 0 0 8px;
    font-size: 17px;
    color: #062963;
    font-weight: 700;
}
.cmx-symptom-card p {
    margin: 0;
    color: #444;
    font-size: 14.5px;
    line-height: 1.55;
}

/* ============================================================
   BLOCK 3: LOCAL TECH STRIP
   ============================================================ */
.cmx-local {
    background: #EBF1FA;
    padding: 40px 20px;
    border-top: 1px solid #d6e3f4;
    border-bottom: 1px solid #d6e3f4;
}
.cmx-local p {
    max-width: 900px;
    margin: 0 auto;
    text-align: center;
    color: #062963;
    font-size: 17px;
    font-weight: 500;
    line-height: 1.6;
}

/* ============================================================
   BLOCK 4: WHY CASPIAN (dark sapphire box)
   ============================================================ */
.cmx-why {
    background: linear-gradient(135deg, #062963 0%, #041d44 100%);
    color: #fff !important;
    padding: 60px 20px;
}
.cmx-why h2 { color: #fff !important; font-size: 28px; margin: 0 0 8px; text-align: center; }
.cmx-why-lead { color: #b8d0eb !important; text-align: center; margin: 0 auto 36px; max-width: 720px; font-size: 16px; }
.cmx-stat-grid {
    display: grid;
    grid-template-columns: repeat(4, 1fr);
    gap: 18px;
    max-width: 1000px;
    margin: 0 auto 32px;
}
.cmx-stat-card {
    background: rgba(255,255,255,0.06);
    border: 1px solid rgba(255,255,255,0.15);
    border-radius: 8px;
    padding: 24px 18px;
    text-align: center;
}
.cmx-stat-num { color: #F4B942 !important; font-size: 36px; font-weight: 700; margin: 0 0 6px; line-height: 1; }
.cmx-stat-label { color: #fff !important; font-size: 14px; font-weight: 600; line-height: 1.3; }
.cmx-service-note {
    max-width: 880px;
    margin: 0 auto;
    background: rgba(244,185,66,0.10);
    border: 1px solid rgba(244,185,66,0.35);
    border-radius: 6px;
    padding: 18px 22px;
    color: #fff !important;
    font-size: 14.5px;
    line-height: 1.6;
}
.cmx-service-note strong { color: #F4B942 !important; }

/* ============================================================
   BLOCK 5: BRAND GRID
   ============================================================ */
.cmx-brands { padding: 60px 20px; background: #fff; }
.cmx-brand-grid {
    display: grid;
    grid-template-columns: repeat(4, 1fr);
    gap: 12px;
    margin-top: 24px;
}
.cmx-brand-card {
    background: #EBF1FA;
    border: 2px solid transparent;
    border-radius: 6px;
    padding: 14px 14px;
    display: flex;
    align-items: center;
    gap: 12px;
    color: #0B3D91;
    text-decoration: none !important;
    font-weight: 600;
    font-size: 14px;
    transition: all .2s;
}
.cmx-brand-card:hover {
    background: #fff;
    border-color: #2E80D1;
    transform: translateY(-1px);
}
.cmx-brand-logo {
    display: inline-block;
    width: 70px;
    height: 22px;
    flex-shrink: 0;
    background-color: #062963;
    -webkit-mask-image: var(--logo);
            mask-image: var(--logo);
    -webkit-mask-repeat: no-repeat;
            mask-repeat: no-repeat;
    -webkit-mask-position: left center;
            mask-position: left center;
    -webkit-mask-size: contain;
            mask-size: contain;
    transition: background-color .2s;
}
.cmx-brand-card:hover .cmx-brand-logo { background-color: #F4B942; }

/* ============================================================
   BLOCK 6: FAQ
   ============================================================ */
.cmx-faq { padding: 60px 20px; background: #EBF1FA; }
.cmx-faq-list { max-width: 900px; margin: 24px auto 0; }
.cmx-faq-item {
    background: #fff;
    border: 1px solid #d6e3f4;
    border-radius: 6px;
    margin-bottom: 12px;
    overflow: hidden;
}
.cmx-faq-item summary {
    list-style: none;
    cursor: pointer;
    padding: 18px 22px;
    font-weight: 700;
    color: #062963;
    font-size: 15.5px;
    user-select: none;
    position: relative;
    padding-right: 50px;
}
.cmx-faq-item summary::-webkit-details-marker { display: none; }
.cmx-faq-item summary::after {
    content: '+';
    position: absolute;
    right: 22px;
    top: 50%;
    transform: translateY(-50%);
    font-size: 22px;
    color: #2E80D1;
    font-weight: 400;
}
.cmx-faq-item[open] summary::after { content: '−'; }
.cmx-faq-item .cmx-faq-body {
    padding: 0 22px 20px;
    color: #444;
    font-size: 15px;
    line-height: 1.65;
}

/* ============================================================
   BLOCK 7: INTERNAL LINKING
   ============================================================ */
.cmx-links { padding: 60px 20px; background: #fff; }
.cmx-links-group { margin-bottom: 40px; }
.cmx-links-group:last-child { margin-bottom: 0; }
.cmx-links-grid {
    display: grid;
    grid-template-columns: repeat(3, 1fr);
    gap: 10px;
    margin-top: 18px;
}
.cmx-link-card {
    display: block;
    padding: 14px 18px;
    background: #EBF1FA;
    border-radius: 6px;
    color: #0B3D91 !important;
    text-decoration: none !important;
    font-weight: 600;
    font-size: 14.5px;
    border: 2px solid transparent;
    transition: all .2s;
}
.cmx-link-card:hover {
    background: #fff;
    border-color: #2E80D1;
    transform: translateY(-1px);
}
.cmx-sister-links {
    display: flex;
    flex-wrap: wrap;
    gap: 12px;
    margin-top: 18px;
}
.cmx-sister-link {
    display: inline-flex;
    align-items: center;
    gap: 8px;
    padding: 10px 18px;
    border: 2px solid #0B3D91;
    border-radius: 6px;
    color: #0B3D91 !important;
    text-decoration: none !important;
    font-weight: 600;
    font-size: 14px;
    background: #fff;
    transition: all .2s;
}
.cmx-sister-link:hover { background: #0B3D91; color: #fff !important; }

/* ============================================================
   BLOCK 8: CTA-FINAL (dark sapphire)
   ============================================================ */
.cmx-cta-final {
    background: linear-gradient(135deg, #062963 0%, #041d44 100%);
    color: #fff !important;
    padding: 70px 20px;
    text-align: center;
}
.cmx-cta-final h3 { color: #fff !important; font-size: 30px; margin: 0 0 12px; font-weight: 700; }
.cmx-cta-final p { color: #b8d0eb !important; font-size: 17px; margin: 0 auto 28px; max-width: 720px; }
.cmx-cta-final .cmx-cta { justify-content: center; }

/* ============================================================
   RESPONSIVE
   ============================================================ */
@media (max-width: 900px) {
    .cmx-symptom-grid { grid-template-columns: repeat(2, 1fr); }
    .cmx-brand-grid { grid-template-columns: repeat(3, 1fr); }
    .cmx-stat-grid { grid-template-columns: repeat(2, 1fr); }
    .cmx-links-grid { grid-template-columns: repeat(2, 1fr); }
    .cmx-hero h1 { font-size: 32px; }
}
@media (max-width: 600px) {
    .cmx-symptom-grid { grid-template-columns: 1fr; }
    .cmx-brand-grid { grid-template-columns: repeat(2, 1fr); }
    .cmx-stat-grid { grid-template-columns: repeat(2, 1fr); }
    .cmx-links-grid { grid-template-columns: 1fr; }
    .cmx-hero { padding: 50px 18px 44px; }
    .cmx-hero h1 { font-size: 26px; }
    .cmx-subtitle { font-size: 15.5px; }
}
</style>

<div class="caspian-matrix-page">

    <?php /* ===================== BLOCK 1: HERO ===================== */ ?>
    <section class="cmx-hero">
        <div class="cmx-hero-inner">
            <p class="cmx-kicker">Local <?php echo esc_html( $city_name ); ?> technicians for <?php echo esc_html( $applow ); ?> repair</p>
            <h1><?php echo esc_html( $appliance . ' Repair in ' . $city_name ); ?></h1>
            <p class="cmx-subtitle">Same-day <?php echo esc_html( $applow ); ?> service across <?php echo esc_html( $city_name ); ?> and surrounding areas. All major brands. Quality out-of-warranty repairs by experienced technicians.</p>
            <ul class="cmx-trust-pills">
                <li>BBB A Accredited</li>
                <li>★ 4.8 / 220+ Google Reviews</li>
                <li>15+ Years of Service</li>
                <li>90-Day Parts &amp; Labour Warranty</li>
            </ul>
            <div class="cmx-cta">
                <a class="cmx-btn-call" href="tel:+14167325905">📞 Call Now</a>
                <a class="cmx-btn-book" href="/contact/">Book Online</a>
            </div>
        </div>
    </section>

    <?php /* ===================== BLOCK 2: SYMPTOMS ===================== */ ?>
    <section class="cmx-symptoms">
        <div class="cmx-inner">
            <h2>Common <?php echo esc_html( $appliance ); ?> Issues We Repair in <?php echo esc_html( $city_name ); ?></h2>
            <p class="cmx-section-lead">If you recognize any of these symptoms in your <?php echo esc_html( $applow_one ); ?>, our <?php echo esc_html( $city_name ); ?> technicians can diagnose and fix it — often the same day.</p>
            <div class="cmx-symptom-grid">
                <?php foreach ( $svc['symptoms'] as $sym ) : ?>
                    <div class="cmx-symptom-card">
                        <h3><?php echo esc_html( $sym['title'] ); ?></h3>
                        <p><?php echo esc_html( $sym['desc'] ); ?></p>
                    </div>
                <?php endforeach; ?>
            </div>
        </div>
    </section>

    <?php /* ===================== BLOCK 3: LOCAL TECH STRIP ===================== */ ?>
    <section class="cmx-local">
        <p>Our technicians live and work in <strong><?php echo esc_html( $city_name ); ?></strong>. We service all major <?php echo esc_html( $applow ); ?> brands across <?php echo esc_html( $city_name ); ?> and surrounding areas — usually same-day, with parts on the truck for common repairs.</p>
    </section>

    <?php /* ===================== BLOCK 4: WHY CASPIAN ===================== */ ?>
    <section class="cmx-why">
        <div class="cmx-inner">
            <h2>15+ Years of <?php echo esc_html( $appliance ); ?> Repair Across Ontario</h2>
            <p class="cmx-why-lead">Caspian Appliance Repair has been serving Ontario homeowners since 2009. Local <?php echo esc_html( $city_name ); ?> technicians, transparent pricing, real warranty.</p>
            <div class="cmx-stat-grid">
                <div class="cmx-stat-card">
                    <p class="cmx-stat-num">15+</p>
                    <p class="cmx-stat-label">Years of Experience</p>
                </div>
                <div class="cmx-stat-card">
                    <p class="cmx-stat-num">220+</p>
                    <p class="cmx-stat-label">★ 4.8 Google Reviews</p>
                </div>
                <div class="cmx-stat-card">
                    <p class="cmx-stat-num">BBB A</p>
                    <p class="cmx-stat-label">Accredited Business</p>
                </div>
                <div class="cmx-stat-card">
                    <p class="cmx-stat-num">90-Day</p>
                    <p class="cmx-stat-label">Parts &amp; Labour Warranty</p>
                </div>
            </div>
            <?php if ( $is_gas ) : ?>
            <div class="cmx-service-note">
                <strong>Gas-line work disclosure:</strong> Gas appliance repairs in <?php echo esc_html( $city_name ); ?> are performed by certified <strong>TSSA-licensed partner technicians</strong>, in compliance with Ontario regulations. We are independent and not factory-authorized for warranty work — we provide quality out-of-warranty repairs.
            </div>
            <?php else : ?>
            <div class="cmx-service-note">
                <strong>Service note:</strong> We are an independent appliance-repair company and not factory-authorized for warranty work. If your <?php echo esc_html( $applow_one ); ?> is still under manufacturer warranty, contact the manufacturer first. For out-of-warranty repairs in <?php echo esc_html( $city_name ); ?>, we offer fast, quality service backed by our 90-day warranty.
            </div>
            <?php endif; ?>
        </div>
    </section>

    <?php /* ===================== BLOCK 5: BRAND GRID ===================== */ ?>
    <section class="cmx-brands">
        <div class="cmx-inner">
            <h2>We Service All Major <?php echo esc_html( $appliance ); ?> Brands in <?php echo esc_html( $city_name ); ?></h2>
            <p class="cmx-section-lead">From mainstream to high-end, our technicians repair <?php echo esc_html( $applow ); ?>s from every brand we list below.</p>
            <div class="cmx-brand-grid">
                <?php foreach ( $brands as $b ) :
                    $logo_key = strtolower( $b['label'] );
                    $logo_key = str_replace( '&', '', $logo_key );
                    $logo_key = trim( preg_replace( '/\s+/', '-', $logo_key ), '-' );
                    $has_logo = isset( $brand_logos[ $logo_key ] );
                ?>
                    <a class="cmx-brand-card" href="/<?php echo esc_attr( $b['slug'] ); ?>/">
                        <?php if ( $has_logo ) : ?>
                            <span class="cmx-brand-logo" style="--logo:url('<?php echo esc_attr( $brand_logos[ $logo_key ] ); ?>');" aria-hidden="true"></span>
                        <?php endif; ?>
                        <span><?php echo esc_html( $b['label'] ); ?></span>
                    </a>
                <?php endforeach; ?>
            </div>
        </div>
    </section>

    <?php /* ===================== BLOCK 6: FAQ ===================== */ ?>
    <section class="cmx-faq">
        <div class="cmx-inner">
            <h2>Frequently Asked Questions</h2>
            <p class="cmx-section-lead"><?php echo esc_html( $appliance ); ?> repair in <?php echo esc_html( $city_name ); ?> — quick answers to common questions.</p>
            <div class="cmx-faq-list">
                <?php foreach ( $faqs as $f ) : ?>
                    <details class="cmx-faq-item">
                        <summary><?php echo esc_html( $f['q'] ); ?></summary>
                        <div class="cmx-faq-body"><?php echo esc_html( $f['a'] ); ?></div>
                    </details>
                <?php endforeach; ?>
            </div>
        </div>
    </section>

    <?php /* ===================== BLOCK 7: INTERNAL LINKING ===================== */ ?>
    <section class="cmx-links">
        <div class="cmx-inner">

            <div class="cmx-links-group">
                <h2>Other Appliance Repair in <?php echo esc_html( $city_name ); ?></h2>
                <p class="cmx-section-lead">We repair every major appliance in <?php echo esc_html( $city_name ); ?>:</p>
                <div class="cmx-links-grid">
                    <?php foreach ( $other_services as $os ) : ?>
                        <a class="cmx-link-card" href="<?php echo esc_url( $os['url'] ); ?>"><?php echo esc_html( $os['label'] ); ?> in <?php echo esc_html( $city_name ); ?> →</a>
                    <?php endforeach; ?>
                </div>
            </div>

            <?php if ( ! empty( $nearby_cities ) ) : ?>
            <div class="cmx-links-group">
                <h2><?php echo esc_html( $appliance ); ?> Repair in Nearby Cities</h2>
                <p class="cmx-section-lead">We serve <?php echo esc_html( $appliance ); ?> repair across the wider region:</p>
                <div class="cmx-links-grid">
                    <?php foreach ( array_slice( $nearby_cities, 0, 9 ) as $nc ) : ?>
                        <a class="cmx-link-card" href="<?php echo esc_url( $nc['url'] ); ?>"><?php echo esc_html( $nc['label'] ); ?> →</a>
                    <?php endforeach; ?>
                </div>
            </div>
            <?php endif; ?>

            <div class="cmx-links-group">
                <h2>Looking for Broader Pages?</h2>
                <p class="cmx-section-lead">Browse the general service page or the full <?php echo esc_html( $city_name ); ?> overview:</p>
                <div class="cmx-sister-links">
                    <a class="cmx-sister-link" href="<?php echo esc_url( $svc['parent_url'] ); ?>">All <?php echo esc_html( $appliance ); ?> Repair →</a>
                    <a class="cmx-sister-link" href="<?php echo esc_url( caspian_matrix_city_url( $city_slug ) ); ?>">All Appliance Repair in <?php echo esc_html( $city_name ); ?> →</a>
                    <a class="cmx-sister-link" href="/service-areas/">All Service Areas →</a>
                </div>
            </div>

        </div>
    </section>

    <?php /* ===================== BLOCK 8: CTA-FINAL ===================== */ ?>
    <section class="cmx-cta-final">
        <h3>Need <?php echo esc_html( $appliance ); ?> Repair in <?php echo esc_html( $city_name ); ?>?</h3>
        <p>Call now or book online. Same-day appointments often available across <?php echo esc_html( $city_name ); ?> and surrounding areas.</p>
        <div class="cmx-cta">
            <a class="cmx-btn-call" href="tel:+14167325905">📞 Call Now</a>
            <a class="cmx-btn-book" href="/contact/">Book Online</a>
        </div>
    </section>

</div>
    <?php
    return ob_get_clean();
}
